// NotPetya Crisis Timeline — three-phase reconstruction
// Sources: Wikipedia (EternalBlue, 2017 Ukraine ransomware attacks, Petya family),
// WIRED (Greenberg, Maersk story), Microsoft MSRC, CCDCOE cyberlaw toolkit, DNA, hypr.com.

window.TIMELINE_EVENTS = [
  // ═══════════════════════════════════════════════════════════════
  // PHASE 1 — PRE-CRISIS BUILD-UP (Weaponization)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'e01',
    phase: 'prelude',
    date: '2013-09',
    dateLabel: 'c. 2013',
    t: 0.00,
    title: 'EternalBlue is developed inside the NSA',
    location: 'Fort Meade, Maryland',
    coords: [39.1, -76.7],
    severity: 1,
    kind: 'intelligence',
    headline: 'A zero-day SMBv1 exploit is weaponized inside the NSA\'s Tailored Access Operations unit.',
    body: 'Offensive engineers at the NSA weaponize a flaw in Microsoft\'s Server Message Block (SMBv1) protocol. The exploit — codenamed ETERNALBLUE — enables remote code execution on almost any unpatched Windows machine on a network. It is paired with a backdoor installer (DOUBLEPULSAR) and reportedly used in live operations for years. Microsoft is not told.',
    artifacts: ['ETERNALBLUE (exploit)', 'DOUBLEPULSAR (implant)', 'FUZZBUNCH (framework)'],
  },
  {
    id: 'e02',
    phase: 'prelude',
    date: '2016-08-13',
    dateLabel: 'August 13, 2016',
    t: 0.05,
    title: 'The Shadow Brokers appear',
    location: 'Anonymous / online',
    coords: [55.0, 37.0],
    severity: 2,
    kind: 'leak',
    headline: 'An anonymous group begins auctioning stolen NSA cyberweapons.',
    body: 'A group calling itself "The Shadow Brokers" posts a sample of tools stolen from the NSA-linked Equation Group and announces an auction. Researchers confirm the sample is real. Russian intelligence is widely suspected. The auction fails — and the group rotates through escalating release strategies.',
    artifacts: ['Public GitHub dump', 'Bitcoin auction wallet'],
  },
  {
    id: 'e03',
    phase: 'prelude',
    date: '2017-03-14',
    dateLabel: 'March 14, 2017',
    t: 0.12,
    title: 'Microsoft ships MS17-010',
    location: 'Redmond, WA',
    coords: [47.6, -122.1],
    severity: 2,
    kind: 'defense',
    headline: 'Microsoft silently patches the exact SMBv1 flaws EternalBlue exploits — no reporter, no CVE credit.',
    body: 'Security bulletin MS17-010 quietly closes the SMBv1 vulnerabilities. No CVE reporter is named. Observers conclude the NSA, fearing imminent leak, warned Microsoft. The patch ships — but worldwide patching cycles take months, and many industrial and embedded systems never receive it.',
    artifacts: ['MS17-010 bulletin', 'Windows Update rollout'],
  },
  {
    id: 'e04',
    phase: 'prelude',
    date: '2017-04-14',
    dateLabel: 'April 14, 2017',
    t: 0.19,
    title: '"Lost in Translation" dump — EternalBlue goes public',
    location: 'Public internet',
    coords: [50.1, 14.4],
    severity: 3,
    kind: 'leak',
    headline: 'The Shadow Brokers publish the full NSA toolkit. A nation-state exploit is now globally accessible.',
    body: 'On Good Friday, Shadow Brokers release a trove titled "Lost in Translation" — EternalBlue, DoublePulsar, EternalRomance, EternalChampion and a chaining framework. Within 24 hours, scanners map hundreds of thousands of vulnerable hosts. This is the critical enabling event: the floor collapses beneath every unpatched Windows machine on the internet.',
    artifacts: ['Public exploit code', 'DoublePulsar beacons in the wild'],
  },
  {
    id: 'e05',
    phase: 'prelude',
    date: '2017-05-12',
    dateLabel: 'May 12, 2017',
    t: 0.26,
    title: 'WannaCry — the warning shot',
    location: 'Global, DPRK-attributed',
    coords: [39.0, 125.7],
    severity: 4,
    kind: 'attack',
    headline: 'A ransomware worm using EternalBlue cripples the UK NHS, Telefónica, FedEx and 200,000+ hosts.',
    body: 'WannaCry spreads worldwide in hours, encrypting files and demanding $300 in Bitcoin. UK NHS hospitals reroute ambulances. Researcher Marcus Hutchins registers a hard-coded kill-switch domain and halts it by accident. Microsoft issues emergency patches even for end-of-life Windows XP. The signal is loud — and the world ignores it. Patching gaps remain massive.',
    artifacts: ['Kill-switch domain', 'Emergency XP patch', 'NHS outage reports'],
    casualties: '~200,000 infections, 150 countries',
    damageUSD: '$4–8B (est.)',
  },
  {
    id: 'e06',
    phase: 'prelude',
    date: '2017-05-18',
    dateLabel: 'May 18, 2017',
    t: 0.32,
    title: 'XData — the rehearsal',
    location: 'Ukraine',
    coords: [50.45, 30.52],
    severity: 2,
    kind: 'intrusion',
    headline: 'Ukrainian companies hit by XData ransomware — propagating through the M.E.Doc update channel.',
    body: 'A first attack dubbed XData spreads in Ukraine via a compromised M.E.Doc update. The outbreak is limited. In retrospect, this is an access-validation phase: Sandworm has already compromised the Linkos Group update infrastructure. They are testing propagation, credential harvesting, and lateral movement. The main payload is still six weeks away.',
    artifacts: ['M.E.Doc update infrastructure', 'Stolen code-signing keys'],
  },
  {
    id: 'e07',
    phase: 'prelude',
    date: '2017-05-20',
    dateLabel: 'May–June 2017',
    t: 0.36,
    title: 'Covert preparation',
    location: 'Kyiv, Ukraine',
    coords: [50.45, 30.52],
    severity: 2,
    kind: 'intrusion',
    headline: 'Sandworm (GRU Unit 74455) retains persistence inside Linkos Group.',
    body: 'During May and June, attackers keep covert access to the M.E.Doc update servers. They weaponize a payload combining EternalBlue (network worm) + EternalRomance + credential harvesting (Mimikatz) + lateral movement via PsExec and WMIC — a hybrid designed to pierce any segmented network. The ransom note is a deliberate misdirection.',
  },

  // ═══════════════════════════════════════════════════════════════
  // PHASE 2 — THE CRISIS (June 27, 2017 — Day 0)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'e08',
    phase: 'detonation',
    date: '2017-06-27T10:30',
    dateLabel: 'Jun 27 · morning · Kyiv',
    t: 0.42,
    title: 'Day 0 — the poisoned M.E.Doc update',
    location: 'Kyiv, Ukraine',
    coords: [50.45, 30.52],
    severity: 5,
    kind: 'attack',
    headline: 'A malicious update ships to every installed copy of Ukraine\'s dominant tax-accounting software.',
    body: 'One day before Ukraine\'s Constitution Day holiday, Sandworm pushes the update. Thousands of Ukrainian businesses, banks and government agencies install it automatically. Any company filing taxes in Ukraine runs M.E.Doc — tax/accounting dependency creates systemic exposure. Infection begins within minutes.',
    artifacts: ['ezvit.exe (M.E.Doc updater)', 'perfc.dat payload', 'Fake ransom note'],
  },
  {
    id: 'e09',
    phase: 'detonation',
    date: '2017-06-27T11:30',
    dateLabel: 'Jun 27 · late morning',
    t: 0.46,
    title: 'Ukrainian critical infrastructure collapses',
    location: 'Kyiv / nationwide',
    coords: [50.45, 30.52],
    severity: 5,
    kind: 'impact',
    headline: 'Within an hour, ~10% of all computers in Ukraine are wiped.',
    body: 'Oschadbank, Ukrposhta, Kyiv Metro payment, Boryspil Airport, Chernobyl radiation monitors, Ukrenergo grid terminals, ministries — all hit simultaneously. ATMs display skulls. Chernobyl radiation sensors switch to manual. Early media coverage misclassifies it as ransomware. Ukraine\'s deputy prime minister posts a photo of a blue screen and writes "Ta-daa!"',
    casualties: '~10% of Ukrainian computers wiped',
  },
  {
    id: 'e10',
    phase: 'detonation',
    date: '2017-06-27T12:00',
    dateLabel: 'Jun 27 · ~noon UTC',
    t: 0.50,
    title: 'Maersk: 17 minutes to global blackout',
    location: 'Copenhagen → worldwide',
    coords: [55.68, 12.57],
    severity: 5,
    kind: 'impact',
    headline: 'The world\'s largest shipping company loses every domain controller — except one, by accident.',
    body: 'A.P. Møller-Maersk handles ~20% of global container shipping. In 17 minutes NotPetya destroys 49,000 laptops, 4,000 servers, and all 150 domain controllers. The company cannot invoice, route ships, or open gate cranes at 76 terminals. A single domain controller in Ghana survived — offline during a power outage. Its hard drive is flown to the UK under escort. It becomes the seed of the entire rebuild.',
    artifacts: ['The Ghana domain controller', 'Emergency WhatsApp coordination', 'Handwritten bills of lading'],
    casualties: '49,000 laptops + 4,000 servers destroyed',
    damageUSD: '$300M',
  },
  {
    id: 'e11',
    phase: 'detonation',
    date: '2017-06-27T13:00',
    dateLabel: 'Jun 27 · afternoon',
    t: 0.54,
    title: 'Merck: vaccine production halts',
    location: 'Kenilworth, NJ / global',
    coords: [40.68, -74.29],
    severity: 5,
    kind: 'impact',
    headline: 'Merck loses ~40,000 devices. HPV vaccine Gardasil production stops.',
    body: 'Pharmaceutical giant Merck is among the first US multinationals hit. Research labs, manufacturing lines and supply-chain systems all wiped. The CDC loans Merck doses of Gardasil from the US strategic stockpile. Merck will later file — and eventually win — the landmark $1.4 billion insurance case.',
    casualties: '~40,000 devices destroyed',
    damageUSD: '$870M direct / $1.4B claim',
  },
  {
    id: 'e12',
    phase: 'detonation',
    date: '2017-06-27T14:00',
    dateLabel: 'Jun 27 · afternoon',
    t: 0.57,
    title: 'FedEx / TNT Express — Europe paralyzed',
    location: 'Hoofddorp, Netherlands',
    coords: [52.30, 4.69],
    severity: 4,
    kind: 'impact',
    headline: 'FedEx\'s European subsidiary TNT is comprehensively wiped. Some systems never fully recover.',
    body: 'TNT Express — acquired by FedEx only a year earlier — reverts to manual processes: paper labels, phone calls, physically couriering package data between hubs. Integration with FedEx\'s systems is set back by years. FedEx books $400M in NotPetya-related damages in SEC filings.',
    damageUSD: '$400M',
  },
  {
    id: 'e13',
    phase: 'detonation',
    date: '2017-06-27T15:00',
    dateLabel: 'Jun 27 · afternoon',
    t: 0.60,
    title: 'Mondelēz, Saint-Gobain, Reckitt, WPP, Rosneft…',
    location: 'Global',
    coords: [48.85, 2.35],
    severity: 4,
    kind: 'impact',
    headline: 'The worm jumps every VPN it finds. Oreo, Cadbury, Durex, Nurofen production halts.',
    body: 'Mondelēz loses 1,700 servers and 24,000 laptops. Saint-Gobain (construction) loses €250M. Reckitt Benckiser (Durex, Nurofen) reports £100M of lost revenue. WPP (advertising) is hit. Rosneft — a Russian state oil major — is hit too. Russia is not spared from its own weapon.',
    casualties: 'Dozens of multinationals',
    damageUSD: '€250M (Saint-Gobain) · £100M (Reckitt) · $180M (Mondelēz)',
  },
  {
    id: 'e14',
    phase: 'detonation',
    date: '2017-06-27T20:00',
    dateLabel: 'Jun 27 · evening',
    t: 0.63,
    title: 'Global incident declared',
    location: 'Worldwide',
    coords: [51.51, -0.12],
    severity: 4,
    kind: 'defense',
    headline: 'Major cybersecurity firms declare a global incident. Companies disconnect at scale.',
    body: 'Mandiant, Kaspersky, ESET, Cisco Talos all issue urgent advisories. Companies begin emergency actions: disconnecting networks, shutting down data centers, pulling the physical cables from critical systems. Maersk disconnects its entire global infrastructure within hours. Key signals emerge: no kill switch, a single Bitcoin wallet, and — crucially — this looks nothing like profit-driven crime.',
  },
  {
    id: 'e15',
    phase: 'detonation',
    date: '2017-06-28',
    dateLabel: 'Jun 28 · Day +1',
    t: 0.66,
    title: 'Supply-chain compromise confirmed',
    location: 'Microsoft MSRC · researchers',
    coords: [44.43, 26.10],
    severity: 3,
    kind: 'analysis',
    headline: 'Microsoft and Cybereason identify M.E.Doc as Patient Zero. A "perfc" vaccine is published.',
    body: 'Microsoft publishes its analysis pointing to the M.E.Doc update as the entry vector. Amit Serper at Cybereason and others discover a local vaccine — a read-only C:\\Windows\\perfc file — but the wave has already passed. The scale becomes clear: thousands of companies in 65+ countries, Ukraine the primary target.',
  },

  // ═══════════════════════════════════════════════════════════════
  // PHASE 3 — POST-CRISIS: FORENSICS, LAW, DOCTRINE
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'e16',
    phase: 'fallout',
    date: '2017-06-30',
    dateLabel: 'Jun 29–30 · Days +2/+3',
    t: 0.70,
    title: 'It is not ransomware — it is a wiper',
    location: 'Global research community',
    coords: [31.78, 35.21],
    severity: 3,
    kind: 'analysis',
    headline: 'Reverse-engineering proves recovery is impossible. The ransom channel collapses.',
    body: 'The malware overwrites the Master Boot Record and Master File Table with no recoverable mapping. The "installation ID" shown to victims is random bytes. The ransom email provider shuts the drop address down. Narrative pivots: this was never cybercrime — it was a destructive cyber operation dressed as one. Kaspersky names it NotPetya; Matt Suiche calls it a wiper.',
  },
  {
    id: 'e17',
    phase: 'fallout',
    date: '2017-07-01',
    dateLabel: 'Jul 1 · Day +4',
    t: 0.73,
    title: 'Ukraine points at Russia',
    location: 'Kyiv',
    coords: [50.45, 30.52],
    severity: 2,
    kind: 'attribution',
    headline: 'Early government signals attribute the attack to Russian actors.',
    body: 'The SBU and Ukrainian officials publicly accuse Russian intelligence of orchestrating the attack. The CCDCOE Tallinn-based legal toolkit begins assessing its status under international law — a question with no clean answer, and one that will shape insurance disputes for a decade.',
  },
  {
    id: 'e18',
    phase: 'fallout',
    date: '2017-07-05',
    dateLabel: 'First week of July',
    t: 0.76,
    title: 'Peak operational chaos',
    location: 'Worldwide',
    coords: [40.71, -74.01],
    severity: 4,
    kind: 'impact',
    headline: 'Global supply chains, logistics, pharma, manufacturing operate in degraded mode for weeks.',
    body: 'Cumulative damage estimates cross $10 billion — making NotPetya the most expensive cyber event in history. Ports accumulate backlogs. Pharmacy supply is tight. Manufacturing plants run on paper. Many firms remain in degraded mode for weeks; some never restore full function.',
    damageUSD: '$10B+ global',
  },
  {
    id: 'e19',
    phase: 'fallout',
    date: '2017-07-07',
    dateLabel: '~10 days after',
    t: 0.79,
    title: 'Maersk rebuilds in ten days',
    location: 'Global Maersk operations',
    coords: [51.51, -0.13],
    severity: 2,
    kind: 'recovery',
    headline: '10 days · 4,000 new servers · 45,000 new PCs — reinstalled from the Ghana domain controller.',
    body: 'Supported by Deloitte and thousands of contractors, Maersk rebuilds its entire global network in ten days using the single surviving Ghana DC as seed. Through the outage, the company processes shipping manually on WhatsApp and Gmail. CEO Søren Skou says publicly the company had "a serious business issue."',
    damageUSD: '$300M',
  },
  {
    id: 'e20',
    phase: 'fallout',
    date: '2018-02-15',
    dateLabel: 'February 15, 2018',
    t: 0.83,
    title: 'Five-Eyes attribution: Russian military',
    location: 'Washington · London · Canberra',
    coords: [51.50, -0.12],
    severity: 3,
    kind: 'attribution',
    headline: 'The White House, UK, Canada, Australia and New Zealand blame GRU Unit 74455 — "Sandworm."',
    body: 'In a coordinated Five-Eyes statement, NotPetya is attributed to the Russian military. The White House calls it "the most destructive and costly cyber-attack in history." Total damages are pegged at over $10 billion. No NotPetya-specific sanctions are imposed at the time.',
    damageUSD: '$10B+ (global est.)',
  },
  {
    id: 'e21',
    phase: 'fallout',
    date: '2018-12',
    dateLabel: '2018 — 2020',
    t: 0.86,
    title: 'Insurers invoke "act of war"',
    location: 'New Jersey · Illinois · London',
    coords: [40.71, -74.01],
    severity: 4,
    kind: 'insurance',
    headline: 'Mondelēz sues Zurich. Merck sues ACE and dozens of carriers. Century-old war exclusions are dusted off.',
    body: 'Mondelēz\'s $100M claim and Merck\'s $1.4B claim are denied under "hostile or warlike action" exclusions written for conventional warfare. Insurers argue the US attribution to the Russian military makes NotPetya an act of war. The cyber insurance industry holds its breath — the outcome will define whether state-sponsored attacks are insurable at all.',
  },
  {
    id: 'e22',
    phase: 'fallout',
    date: '2020-10-19',
    dateLabel: 'October 19, 2020',
    t: 0.89,
    title: 'DOJ indicts six GRU officers',
    location: 'Western District of Pennsylvania',
    coords: [40.44, -79.99],
    severity: 3,
    kind: 'attribution',
    headline: 'The US DOJ names six Sandworm officers by face and passport.',
    body: 'An indictment charges six GRU Unit 74455 officers by name for NotPetya, the 2015/2016 Ukrainian power-grid attacks, Olympic Destroyer (PyeongChang 2018), and interference in the 2017 French election. They are unlikely to ever stand trial — but their photos are now on FBI wanted posters.',
  },
  {
    id: 'e23',
    phase: 'fallout',
    date: '2022-01-14',
    dateLabel: 'January 2022',
    t: 0.93,
    title: 'Merck wins. $1.4 billion.',
    location: 'Union County, NJ',
    coords: [40.66, -74.39],
    severity: 3,
    kind: 'insurance',
    headline: 'A New Jersey court rules NotPetya was NOT an act of war under Merck\'s all-risk policy.',
    body: 'Superior Court Judge Thomas Walsh rules the "hostile/warlike action" exclusion cannot be stretched to cover state-sponsored cyberattacks on commercial infrastructure. Merck is entitled to the full $1.4 billion. The ruling is upheld on appeal in 2023. Mondelēz settles with Zurich on undisclosed terms. The precedent stands.',
    damageUSD: '$1.4B awarded',
  },
  {
    id: 'e24',
    phase: 'fallout',
    date: '2023-03-31',
    dateLabel: 'March 31, 2023',
    t: 0.97,
    title: 'Lloyd\'s rewrites the market',
    location: 'Lloyd\'s of London',
    coords: [51.51, -0.08],
    severity: 2,
    kind: 'insurance',
    headline: 'Market Bulletin Y5381: all standalone cyber policies must now exclude state-backed cyberattacks.',
    body: 'Lloyd\'s requires every standalone cyber policy written by its syndicates from 31 March 2023 to carry explicit exclusions for losses arising from state-backed cyberattacks. The NotPetya precedent reshapes cyber insurance globally: tighter exclusions, higher premiums, reduced coverage scope. The doctrine lands: NotPetya is the first large-scale cyber weapon with global collateral damage — and insurance must price it as such.',
    damageUSD: '$10–15B cumulative',
  },
];

window.PHASES = [
  { id: 'prelude', label: 'Pre-crisis · Weaponization', range: '2013 — May 2017', start: 0.00, end: 0.40, tint: 'var(--amber)' },
  { id: 'detonation', label: 'The Crisis', range: 'Jun 27, 2017 — Day 0', start: 0.40, end: 0.68, tint: 'var(--red)' },
  { id: 'fallout', label: 'Post-crisis · Years-long fallout', range: 'Jul 2017 — 2023', start: 0.68, end: 1.00, tint: 'var(--ash)' },
];
